# Generated by Django 2.0 on 2019-03-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='spaces.Space'),
        ),
    ]
