# Generated by Django 2.0 on 2019-03-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_userrate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrate',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
