# Generated by Django 2.0 on 2019-03-23 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0003_auto_20190323_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
