# Generated by Django 2.0 on 2019-03-26 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0004_auto_20190326_0337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrate',
            unique_together={('user', 'space')},
        ),
    ]
