# Generated by Django 2.0 on 2019-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_auto_20190326_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='userrate',
            name='calm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrate',
            name='clean',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrate',
            name='internet',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrate',
            name='location',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userrate',
            name='staff',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
