# Generated by Django 2.0 on 2019-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_auto_20190329_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='air_conditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='drinks_foods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='laptop_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='open_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
