# Generated by Django 2.0 on 2019-06-13 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_auto_20190609_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
