# Generated by Django 2.0 on 2019-06-13 23:24

from django.db import migrations, models
import django.db.models.deletion
import spaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_space_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/room/%Y/%m/%d/', validators=[spaces.models.SpaceImages.validate_image])),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.Space')),
            ],
        ),
    ]
