# Generated by Django 2.0 on 2019-06-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0015_auto_20190621_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrate',
            name='calm',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='clean',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='feedback',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='internet',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='location',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='staff',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
    ]
